### ISSUE TITLE
Questions about future features

### ISSUE THREAD

**Issue by icefoxen** [manuel-woelker/rust-vfs#1]
I'm writing a game engine that needs a VFS layer (similar to physfs) and this crate caught my eye, but it would need a couple more features to be applicable.

* Virtual roots, so you could create a VFS rooted in `/home/username/.local/game/data` and your VFS would essentially use that as its root directory
* Overlays, so you could effectively merge a filesystem tree with a zip file tree

Would you be interested in accepting pull requests that implement these feature for VFS, or do they not fit with your goals?

**Comment by manuel-woelker** [comment]
These would be great additions, and I'd be looking forward to pull request.

Regarding API stability, I'm currently not sure the API is sufficient/practical for the common use cases.
But I'd love to hear feedback based on another consumer perspective.

**Comment by icefoxen** [comment]
Revisiting this at last after digging into the PhysicsFS library and seeing how it does stuff.  My goal is to be able to present similar functionality: have a number of different locations, including archive files, and present a unified virtual filesystem that merges all of them.

One of the problems with this is in fact the `VFS` trait.  It has one method: `fn path<T: Into<String>>(&self, path: T) -> Self::PATH;`  However, you can't actually create a trait object out a `VFS` because it has a generic parameter.  So it's impossible to create a collection of `VFS` objects with different implementations and a uniform interface, which seems like the obvious way of trying to do it.

The other problem is that this merged filesystem only work for filesystem types that all share the same `VPath`, `VFile` and `VMeta` types anyway, but it would be possible to write shims to translate types to do that.

Any thoughts?

**Comment by manuel-woelker** [comment]
I haven't looked into the details myself, but I think it might be possible by using `Box` to abstract over the different implementations/instances. The overlay FS could be a separate struct implementing VFS and having a `Vec` of `Box`es of the various layers.

`OverlayFile` could contain a `Box<VFile>` etc. Not sure if this works in practice, but it might be something to try out.

The initial version of this lib used Boxes instead of generics, that might be an option as well.

**Comment by icefoxen** [comment]
Yeah, that's the approach I was taking.  The problem is that you can't `Box` a `VFS` trait object.

An alternative would be to just make an enum of all the types that implement VFS and do the dispatching ourselves, but that means you have to change that every single time you add a new VFS type.  The sort of thing dynamic dispatch being built into the language is supposed to save us from.

**Comment by flaviojs** [comment]
For me the main issue is paths...
String only allows valid utf8 while OsString and archive entries can have invalid utf8.
PathBuf can be used to manipulate paths, but it is bound to the OS filesystem and has OS-specific capabilities and rules.

A proposal:

Create a concrete VPathBuf with path manipulation capabilities that is unbound to any system and only has one set of rules.
VFS would use it to create a bound path with trait VPath.
VPath would be a path bound to a filesystem (VPathBuf + VFS), would be responsible for interpreting VPathBuf, would interact with the VFS, and would be able to downgrade into a VPathBuf (to manipulate the path or use in other VFS's).

**Comment by sffc** [comment]
Not being able to box a VFS is a big problem for usability.  I want to make a library that uses an in-memory implementation for testing and a filesystem implementation when run as a binary tool, but in order to do that, I need to wrap the VFS trait in my own trait, which seems like it defeats the purpose of a shared library.

**Comment by manuel-woelker** [comment]
Thanks for the comment, I am in the process of experimenting with an erased, boxable version of the VFS.
Still a work in progress, but you can take a look here, and leave some feedback.

https://github.com/manuel-woelker/rust-vfs/blob/fb-erased-fs-trait/src/lib.rs

This change should also enable things like "remounting" filesystems, accessing files in archives, and union/overlay filesystems.

**Comment by sffc** [comment]
Thanks for the reply!

I actually got this working fine by making a generic type `V: VFS` instead of trying to pass a `&VFS` trait object.

**Comment by manuel-woelker** [comment]
@sffc I just released version 0.3.0, which reworked the API to remove the generic type parameters from the API. This should improve handling and ergonomics. It's a breaking change so it might take some legwork to get things compiling again, but it should be relatively straightforward. If you have any issues or feedback please let me know!

**Comment by manuel-woelker** [comment]
Closing since this should be fixed now, please feel free to open a new issue if you have any further problems.
