### ISSUE TITLE
Cannot easily copy directory to root of new filesystem

### ISSUE THREAD

**Issue by MaulingMonkey** [manuel-woelker/rust-vfs#11]
Ran into this while creating a zip writing filesystem.  If the zip filesystem starts out assuming "" exists, `copy_dir` immediately fails (despite the fact that it's empty).  Alternatively, if the root filesystem must be created, `get_parent` fails slightly later.  Possible fixes include:

* Making get_parent on `None` successful?
* Allowing empty destination directories?
* Allowing merges with a destination directory?
* Some combination thereof?

### Relevant code

https://github.com/manuel-woelker/rust-vfs/blob/c34f4cadba77593643aaab5c4f33c23bab25b4e1/src/path.rs#L400-L406

https://github.com/manuel-woelker/rust-vfs/blob/c34f4cadba77593643aaab5c4f33c23bab25b4e1/src/path.rs#L130-L131

https://github.com/manuel-woelker/rust-vfs/blob/c34f4cadba77593643aaab5c4f33c23bab25b4e1/src/path.rs#L182-L191

[vfs-zip/examples/copy-early-vfs-zip.rs](https://github.com/MaulingMonkey/vfs-zip/blob/972a99f515fe978e9b879bb170a3a0c3e7e633cf/examples/copy-early-vfs-zip.rs#L5-L10) lines 5-10:
**NOTE:** Current example code succeeds because I copy to a subdirectory.
```rust
fn main() {
    create_dir_all("target/tmp").unwrap();;
    let src = VfsPath::new(ZipReadOnly::new_strict(File::open("test/data/early-vfs-zip.zip").unwrap()).unwrap());
    let dst = VfsPath::new(ZipWriteOnly::new_weak(File::create("target/tmp/early-vfs-zip-copy.zip").unwrap()).unwrap());
    // NOTE: https://github.com/MaulingMonkey/vfs-zip/issues/1
    let copied = src.copy_dir(&dst.join("subdir").unwrap()).unwrap();
```

**Comment by manuel-woelker** [comment]
The code currently assumes that the root directory already exists.

Could you explain what your use case is? I had originally envisioned mounting zip files as "packed asset directories", but only in a read-only fashion.

Writing to zip files through a vfs interface seems really hard, since the zip files store entries sequentially and there is zip directory at the end that needs to be written. Additionally I dont thinks zip files have a notion of directories.

**Comment by MaulingMonkey** [comment]
> Could you explain what your use case is?

I have two in mind:

1. Creating those packed asset directories in the first place.  I might want an asset compilation system writing directly to the filesystem... or to multi-stage caches... or to a packed asset directory.

2. Creating bundled game saves.  Factorio among others use `.zip` or similar formats.  For dev or PC builds it can be convenient to keep the files in a loose directory format for easier inspection - but some console savegame APIs only allow single files IIRC, so you need to bundle things up for those formats.

For the latter case it might be more appropriate to resort to a MemoryFS wrapper that fully reads a zip on `new` and saves the zip out on `drop` than the ReadOnly/WriteOnly pair I have now, but a filesystem-like abstraction still seems reasonable.

> Writing to zip files through a vfs interface seems really hard, since the zip files store entries sequentially and there is zip directory at the end that needs to be written.

Their sequential nature does force a sync point (in my demo, a mutex).  Writing the same file multiple times with the same vfs is wasteful, since previous entries won't be removed - although that's less of a problem for VFSes used once.  You do need to track metadata in memory until you're done with the VFS, but that's doable true.

> Additionally I dont thinks zip files have a notion of directories.

Going through the raw "file" table of my example zip in that repository, you'll see a 0-size "file" entry for ".vscode/" in my demo zip, for example, configuring relatively unimportant metadata - permissions and modification timestamps.  It's more of an optional afterthought than a core part of the zip spec, granted, but they're kinda there :smile:

**Comment by manuel-woelker** [comment]
Ah I see. These use cases are kinda "write-only" in the sense that they are basically written in one go and then read at a later date. There should be no "interleaved" reads and writes, correct?

It might be simpler to have a separate abstraction for the write path. For example an trait mirroring `zip::write::ZipWriter` which would either delegate to an actual `ZipWriter`, or a directory based implementation, which stores these files "unzipped" in a directory (and which could be based on vfs). The read path could still be vfs based.

This would better reflect the constraints of such archive formats, and circumvents the impedance mismatch between these archive constraints and general filesystems capabilities.

If you want to use the VFS for the write path, another approach might be viable. I think the core issue is that the root filesystem must exist, while `copy_dir`, requires the destination to _not_ exist. The simplest way out of this might be to simply loop over all entries in the source directory and call `copy_dir`/`copy_file` for each of them. A bit more legwork, but should do the trick.

Another approach to zip files might be to make a wrapping "zip aware" filesystem. This would delegate all calls to the wrapped filesystem, but all accesses to directories ending in ".zip" are mapped to a ZIP file at that location. Different trade-offs and it might not work for your use case.

**Comment by MaulingMonkey** [comment]
> Ah I see. These use cases are kinda "write-only" in the sense that they are basically written in one go and then read at a later date. There should be no "interleaved" reads and writes, correct?

Write-mostly, and read-optional, but not necessarily write-only.  To take a not entirely contrived example for the asset compilation case:
* Say I run <code>build-all-my-game-assets --dest=**\[archive.zip | directory/\]**</code> and abstract those behind a destination VFS to write to.
* This might involve wanting to write out **some/expensive/to/compile/lightmap.png** to archive.zip / directory, which might be missing from the local asset build cache.
* The build tool might attempt to read the *destination* file metadata (file timestamps) or even destination file contents (to calculate SHA1s) to see if the existing destination file, if any, is already up to date - either based on the last modified timestamps of all the input files used to create that dependency, or if the cache might still have a file *hash* despite no longer retaining the file *contents*.
* If the destination file can't be read (NotSupported zip), doesn't exist (directory), is out of date, or doesn't match the expected hash, only then might `build-all-my-game-assets` download dependencies and rebuild the lightmap from scratch.

> It might be simpler to have a separate abstraction for the write path. \[...\]

Simpler, I'll certainly grant :)

> If you want to use the VFS for the write path, another approach might be viable. I think the core issue is that the root filesystem must exist, while copy_dir, requires the destination to not exist.

Yes.

> The simplest way out of this might be to simply loop over all entries in the source directory and call copy_dir/copy_file for each of them. A bit more legwork, but should do the trick.

Works for me, although I suppose I'm left wondering if something along these lines should be upstreamed...? `copy_dir_merge`?

> Another approach to zip files might be to make a wrapping "zip aware" filesystem. This would delegate all calls to the wrapped filesystem, but all accesses to directories ending in ".zip" are mapped to a ZIP file at that location.

Certainly an idea - although I think I'd probably want to build such a thing on top of individual regular & zip filesystems.

**Comment by manuel-woelker** [comment]
`copy_dir_merge` sounds like a neat addition! Let me know how it goes.
