### ISSUE TITLE
Resolving . to current directory

### ISSUE THREAD

**Issue by SuperCuber** [manuel-woelker/rust-vfs#13]
I'd like a way to use the physical filesystem and be able to access files using absolute paths while also using `.` or `path/to/file` for paths relative to my current directory, similar to how I'd use with any `std::fs` method, but I don't see a way to do it in `PhysicalFS`, in fact it specifically protects against it in the `get_path` method.

For a bit of context, I'm making a tool that reads configurations and source files from current directory and writes to files across the user's home directory (actually the user can configure any absolute path).
I want all my filesystem access to go through a global `dyn FileSystem`, that would usually be a `PhysicalFS`, then, in unit tests I want to switch it out for a `MemoryFS` and just run the tool against that.

A workaround I could try would be to prepend the current directory to each path, but I feel like that's pretty unergonomic.

**Comment by manuel-woelker** [comment]
Hi, thanks for the feature suggestion. Great to see new use cases.

I think resolving such relative paths might be out of scope for this project though. I wanted to explicitly disallow "path escaping" to prevent security issues like confused deputies reading user files.

If these paths are provided by the user in e.g a config file, it might make sense to "normalize" these (i.e. replacing `~` or `.`) before resolving them in the VFS. This should also allow more complex scenarios like resolving `$APP_HOME`, `$TMP` or `$PWD`.

It _might_ be possible to write a wrapper implementation of `FileSystem` that does this resolution on the fly but it could be that there are some internals that prevent that.

Hope I could help, cheers!
