### ISSUE TITLE
Adding is_dir() and is_file() to VfsPath

### ISSUE THREAD

**Issue by der-b** [manuel-woelker/rust-vfs#19]
It would be nice, if VfsPath has a method is_dir() and is_file() similar to the implementation of [std::path::PathBuf](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.is_file).

At the moment, one has to write something similar to this:
```rust
path.metadata()?.file_type == VfsFileType::Directory
```
Which I find inconvenient.

**Comment by manuel-woelker** [comment]
That sounds like a great convenience feature. 

I'll take a stab at it over the weekend.
