### ISSUE TITLE
A consistent definition for paths + EmbeddedFS quirk

### ISSUE THREAD

**Issue by Technohacker** [manuel-woelker/rust-vfs#24]
Hello!
I'm in the process of building an implementation of FileSystem for my own use, where I can mount other VFS implementations under a single root. Having some documentation on the FileSystem trait on the sort of paths that the implementation is expected to support would be a huge boon

A specific situation I am dealing with at the moment is the root folder. EmbeddedFS has a quirk with `read_dir` where:

1. On an instance of EmbeddedFS, I _can_ `read_dir("/")` and have a successful Result from it
2. After conversion of the EmbeddedFS instance to a VfsPath directly without any `join()`s, `path.read_dir()` fails with an Error, saying it cannot read ""

You can test this with:
```rs
EmbeddedFS::<RustEmbedRoot>::new().read_dir("/").unwrap().for_each(|x| println!("{}", x.as_str()));

// and

let p: VfsPath = EmbeddedFS::<RustEmbedRoot>::new().into();
p.read_dir().unwrap();
```

With the current implementation of `VfsPath::join`, I can't do `path.join("/")` which is alright, but I'd love to have a consistent definition :)

**Comment by Technohacker** [comment]
Tested the commit and EmbeddedFS works again, thanks!

I'm not sure if this is a pending change, but I believe this line should be _with_ a starting `/`?
https://github.com/manuel-woelker/rust-vfs/blob/2a7309c162319e746fb30eacd31fe86ad6adeb2b/src/filesystem.rs#L8
My implementation receives absolute paths with a starting slash from vfs as of the linked commit, just wanted to know if it was a planned change for later

**Comment by manuel-woelker** [comment]
Hi, thanks for the test and feedback!

You are totally right, all paths (apart from the root path "") start with a slash, I updated the docs - Good catch, much appreciated!
