### ISSUE TITLE
Graceful Failures for InMemory Solutions

### ISSUE THREAD

**Issue by jalcine** [manuel-woelker/rust-vfs#31]
I ran into a situation where [https://github.com/manuel-woelker/rust-vfs/blob/19c1e076ba503376eb06900c936a3e23880bdc28/src/impls/memory.rs#L200](https://github.com/manuel-woelker/rust-vfs/blob/19c1e076ba503376eb06900c936a3e23880bdc28/src/impls/memory.rs#L200) causes my test to panic. It looks like this could be mitigated by calling <code>self.exists()</code> before attempting to pluck the value out or using the <code>Vec::get</code> method to safely get that value out.

(Originally published at: https://jacky.wtf/2022/4/rf/rfC0gc2rn9hwfkifMaPBgeAE)

**Comment by manuel-woelker** [comment]
Good point, thanks for the report! Should be fixed in 0.7.1

**Comment by jalcine** [comment]
Thank you!

(Originally published at: https://jacky.wtf/2022/4/Pe/Pe1yAGt6sFF-R7MqYWQJHco-)
