### ISSUE TITLE
VfsError does not have an easy way to programmatically match against Error Variants

### ISSUE THREAD

**Issue by Technohacker** [manuel-woelker/rust-vfs#33]
Hey again!
Due to the existence of the VfsError::WithContext variant, it's harder to match on a specific error type since there may be multiple nested WithContext error levels to go through. My use case for this is to ignore an error if a file is missing, but to handle all other cases as invalid situations

There is also the situation of certain implementations returning errors like NotFound via std::io::Error rather than the VfsError variants, but I believe that's an implementation specific issue

To work around this, I currently have a function called `get_root_cause` that returns the true root cause of a VfsError, which also normalizes I/O error types to their respective VfsError variant
```rust
fn get_root_cause(err: VfsError) -> VfsError {
    match err {
        VfsError::WithContext { cause, .. } => get_root_cause(*cause),
        VfsError::IoError(ref io_err) => match io_err.kind() {
            io::ErrorKind::NotFound => {
                VfsError::FileNotFound { path: "".into() }
            }
            _ => err,
        },
        _ => err,
    }
}
```

If this fix is alright, I can make a PR for the same. But I wanted to have some discussion on how to proceed with this bug in case there were other solutions available

**Comment by manuel-woelker** [comment]
Thank your for the suggestion, this does indeed seem like common use case.
A PR would me much appreciated! 👍

**Comment by Technohacker** [comment]
If it's alright to have a breaking change, it may also make sense to change the error type to a struct that contains the type of error, along with an optional cause for it. That way `VfsErrorKind` can handle only those error types that make sense from the VFS abstraction, leaving all other error situations to the error source

**Comment by manuel-woelker** [comment]
Hi, sorry, for the late reply. I am not sure using an additional struct is really necessary. Using `source()` should allow getting to the root cause. Can you elaborate on the benefits you see using this approach?

**Comment by Technohacker** [comment]
My main reasoning behind that idea is that you could do an exhaustive match over each error kind, without having to match on WithContext and repeating the match, like how my current implementation of `get_root_cause` works

**Comment by manuel-woelker** [comment]
I see, yeah, that sounds quite a bit more ergonomic. Looking forward to the PR!
