### ISSUE TITLE
Q: Can you run a process in the Vfs Context?

### ISSUE THREAD

**Issue by Zyian** [manuel-woelker/rust-vfs#48]
So far this project works great in regards that I can build the file system that I want to surface to a program by using an OverlayFS to combine all of the directories together. But I want to be able to execute a process on the machine in the local context of this new OverlayFS. So that the process _thinks_ that the files are local to it.

Would this usecase be considered out of scope for this project?

**Comment by manuel-woelker** [comment]
Hi there, thanks for the interest!

Unfortunately this VFS only operates at the API level inside the current rust process, which means all overlay setups are only visible to the current process (and then only when accessing the files via the VFS handles.

For another process to use the overlay would probably require either

1. Recreating the overlay structure in the started process (probably hard if you don't have source access to that code)
2. Using an overlay mechanism at the OS level (maybe overlayfs or via some FUSE mechanism?)
3. *Maybe* via some LD_PRELOAD shenanigans, intercepting `fopen` and the like

Hope that helps! Out of sheer curiosity - what's your specific use case for this feature?

**Comment by Zyian** [comment]
Okay thank you for clearing that up :) I was thinking I might have to do FUSE but wasn't entirely sure.

I'm trying to experiment with a game launcher, often some games have unofficial addons through DirectX injection, like ReShade/GShade for graphical improvements, or more general addons. I wanted to be able to launch the game with any combination (set beforehand) of dll addons, pure vanilla with nothing at all, one instance with everything loaded, or maybe one.

Currently my setup involves using hard symlinks which is causing Windows to think that I have over 500GB of game files (which is more like only 40GB. 

It would have been nice to create the file structure at runtime with a VFS so there's no conflicts in the files.
