### ISSUE TITLE
question: why we need both `tokio` and `async-std` in `async` vfs

### ISSUE THREAD

**Issue by attila-lin** [manuel-woelker/rust-vfs#65]
Just ask is it necessary have two async runtime.

**Comment by manuel-woelker** [comment]
I think the reason is that `tokio` is used for testing and to spawn blocking io, whereas `async_std` is used for the actual filesystem interactions.
Tokio seems to be the more popular async runtime, so it makes sense to ensure that this crate works well with it.

**Comment by attila-lin** [comment]
Thanks for your reply.
