### ISSUE TITLE
Add ability to create intermediate directories, like mkdirp

### ISSUE THREAD

**Issue by sffc** [manuel-woelker/rust-vfs#7]
I was trying to create a file `a/b/c.json` in a new MemoryFS, but I got the following error:

```
Custom { kind: Other, error: "File not found \"b\"" }
```

It would be nice if it could auto-create the intermediate directories.  `mkdir -p` does this when creating directories, for example.

**Comment by manuel-woelker** [comment]
Released in version 0.3.0 (along with breaking API changes) as VfsPath::create_dir_all()

cf. https://docs.rs/vfs/0.3.0/vfs/path/struct.VfsPath.html#method.create_dir_all

Please feel free to reopen if you have any issues!
