### ISSUE TITLE
Method for moving files/dirs

### ISSUE THREAD

**Issue by io12** [manuel-woelker/rust-vfs#9]
It doesn't look like there's any method for moving/renaming files and directories currently. You can delete and recreate files/dirs, but the performance of this can be bad for large files/dirs.

**Comment by manuel-woelker** [comment]
Good point, for moves on the same filesystems there should probably be an optimization to actually call rename(2) and let the kernel do the heavy lifting. Thanks for the feedback, I will look into it.

**Comment by manuel-woelker** [comment]
Added in the latest release (0.4.0). For physical filesystems this should get lowered to syscalls where available.

https://docs.rs/vfs/0.4.0/vfs/path/struct.VfsPath.html#method.copy_file
